name: Render
on:
  push:
    branches: [master]
  pull_request:

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.12'
      - name: Julia Cache
        uses: julia-actions/cache@v3
      - name: Install dependencies
        run: julia --project=docs -e 'using Pkg; Pkg.instantiate()'
      - name: Render and deploy
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          julia --project=docs docs/make.jl --deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}